/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicResetAdminOnetimeRouteImport } from './routes/api/public/reset-admin-onetime'
import { Route as AuthenticatedAdminUsuariosRouteImport } from './routes/_authenticated/admin/usuarios'
import { Route as AuthenticatedAdminRelatoriosRouteImport } from './routes/_authenticated/admin/relatorios'
import { Route as AuthenticatedAdminManutencaoRouteImport } from './routes/_authenticated/admin/manutencao'
import { Route as AuthenticatedAdminFrotaRouteImport } from './routes/_authenticated/admin/frota'
import { Route as AuthenticatedAdminCustosRouteImport } from './routes/_authenticated/admin/custos'
import { Route as AuthenticatedAdminChamadosRouteImport } from './routes/_authenticated/admin/chamados'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicResetAdminOnetimeRoute =
  ApiPublicResetAdminOnetimeRouteImport.update({
    id: '/api/public/reset-admin-onetime',
    path: '/api/public/reset-admin-onetime',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminUsuariosRoute =
  AuthenticatedAdminUsuariosRouteImport.update({
    id: '/admin/usuarios',
    path: '/admin/usuarios',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRelatoriosRoute =
  AuthenticatedAdminRelatoriosRouteImport.update({
    id: '/admin/relatorios',
    path: '/admin/relatorios',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminManutencaoRoute =
  AuthenticatedAdminManutencaoRouteImport.update({
    id: '/admin/manutencao',
    path: '/admin/manutencao',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminFrotaRoute = AuthenticatedAdminFrotaRouteImport.update({
  id: '/admin/frota',
  path: '/admin/frota',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminCustosRoute =
  AuthenticatedAdminCustosRouteImport.update({
    id: '/admin/custos',
    path: '/admin/custos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminChamadosRoute =
  AuthenticatedAdminChamadosRouteImport.update({
    id: '/admin/chamados',
    path: '/admin/chamados',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin/chamados': typeof AuthenticatedAdminChamadosRoute
  '/admin/custos': typeof AuthenticatedAdminCustosRoute
  '/admin/frota': typeof AuthenticatedAdminFrotaRoute
  '/admin/manutencao': typeof AuthenticatedAdminManutencaoRoute
  '/admin/relatorios': typeof AuthenticatedAdminRelatoriosRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/api/public/reset-admin-onetime': typeof ApiPublicResetAdminOnetimeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin/chamados': typeof AuthenticatedAdminChamadosRoute
  '/admin/custos': typeof AuthenticatedAdminCustosRoute
  '/admin/frota': typeof AuthenticatedAdminFrotaRoute
  '/admin/manutencao': typeof AuthenticatedAdminManutencaoRoute
  '/admin/relatorios': typeof AuthenticatedAdminRelatoriosRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/api/public/reset-admin-onetime': typeof ApiPublicResetAdminOnetimeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin/chamados': typeof AuthenticatedAdminChamadosRoute
  '/_authenticated/admin/custos': typeof AuthenticatedAdminCustosRoute
  '/_authenticated/admin/frota': typeof AuthenticatedAdminFrotaRoute
  '/_authenticated/admin/manutencao': typeof AuthenticatedAdminManutencaoRoute
  '/_authenticated/admin/relatorios': typeof AuthenticatedAdminRelatoriosRoute
  '/_authenticated/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/api/public/reset-admin-onetime': typeof ApiPublicResetAdminOnetimeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin/chamados'
    | '/admin/custos'
    | '/admin/frota'
    | '/admin/manutencao'
    | '/admin/relatorios'
    | '/admin/usuarios'
    | '/api/public/reset-admin-onetime'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin/chamados'
    | '/admin/custos'
    | '/admin/frota'
    | '/admin/manutencao'
    | '/admin/relatorios'
    | '/admin/usuarios'
    | '/api/public/reset-admin-onetime'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin/chamados'
    | '/_authenticated/admin/custos'
    | '/_authenticated/admin/frota'
    | '/_authenticated/admin/manutencao'
    | '/_authenticated/admin/relatorios'
    | '/_authenticated/admin/usuarios'
    | '/api/public/reset-admin-onetime'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicResetAdminOnetimeRoute: typeof ApiPublicResetAdminOnetimeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/reset-admin-onetime': {
      id: '/api/public/reset-admin-onetime'
      path: '/api/public/reset-admin-onetime'
      fullPath: '/api/public/reset-admin-onetime'
      preLoaderRoute: typeof ApiPublicResetAdminOnetimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/usuarios': {
      id: '/_authenticated/admin/usuarios'
      path: '/admin/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AuthenticatedAdminUsuariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/relatorios': {
      id: '/_authenticated/admin/relatorios'
      path: '/admin/relatorios'
      fullPath: '/admin/relatorios'
      preLoaderRoute: typeof AuthenticatedAdminRelatoriosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/manutencao': {
      id: '/_authenticated/admin/manutencao'
      path: '/admin/manutencao'
      fullPath: '/admin/manutencao'
      preLoaderRoute: typeof AuthenticatedAdminManutencaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/frota': {
      id: '/_authenticated/admin/frota'
      path: '/admin/frota'
      fullPath: '/admin/frota'
      preLoaderRoute: typeof AuthenticatedAdminFrotaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/custos': {
      id: '/_authenticated/admin/custos'
      path: '/admin/custos'
      fullPath: '/admin/custos'
      preLoaderRoute: typeof AuthenticatedAdminCustosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/chamados': {
      id: '/_authenticated/admin/chamados'
      path: '/admin/chamados'
      fullPath: '/admin/chamados'
      preLoaderRoute: typeof AuthenticatedAdminChamadosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminChamadosRoute: typeof AuthenticatedAdminChamadosRoute
  AuthenticatedAdminCustosRoute: typeof AuthenticatedAdminCustosRoute
  AuthenticatedAdminFrotaRoute: typeof AuthenticatedAdminFrotaRoute
  AuthenticatedAdminManutencaoRoute: typeof AuthenticatedAdminManutencaoRoute
  AuthenticatedAdminRelatoriosRoute: typeof AuthenticatedAdminRelatoriosRoute
  AuthenticatedAdminUsuariosRoute: typeof AuthenticatedAdminUsuariosRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminChamadosRoute: AuthenticatedAdminChamadosRoute,
  AuthenticatedAdminCustosRoute: AuthenticatedAdminCustosRoute,
  AuthenticatedAdminFrotaRoute: AuthenticatedAdminFrotaRoute,
  AuthenticatedAdminManutencaoRoute: AuthenticatedAdminManutencaoRoute,
  AuthenticatedAdminRelatoriosRoute: AuthenticatedAdminRelatoriosRoute,
  AuthenticatedAdminUsuariosRoute: AuthenticatedAdminUsuariosRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicResetAdminOnetimeRoute: ApiPublicResetAdminOnetimeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
